### ISSUE TITLE
Will this repo be updated?

### ISSUE THREAD

**Issue by bowuL** [rsitko92/todo-list-app-microservices#1]
Hello,the last update is 2 years ago,will it be updated in the future?

**Comment by r-sitko** [comment]
Hello
Do you need something concrete to be changed/added to this project?

**Comment by bowuL** [comment]
Hello
At present I have nothing to add,and I have trouble with the interface generate,I can not gen...
now, i ececute `sudo ./protos/run.sh`, then printf this 
![image](https://user-images.githubusercontent.com/41602940/134303939-6e30cdcf-4332-4ce0-b7d7-f42087cb8707.png)

**Comment by bowuL** [comment]
Nothing occured,xx.pb.py or xx.pb2.py

**Comment by r-sitko** [comment]
Hello
Can you try to modify run.sh script with this? SCRIPT_DIR=$(dirname -- $(readlink -f -- $0))
What operating system do you use?
